// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZDJs-q9dUyLlZCM3IbyFbaw8TJezX0M',
    appId: '1:80375516886:web:e132cd5f0d54356c158377',
    messagingSenderId: '80375516886',
    projectId: 'productivity-app-2bf41',
    authDomain: 'productivity-app-2bf41.firebaseapp.com',
    storageBucket: 'productivity-app-2bf41.firebasestorage.app',
    measurementId: 'G-09DWJMMFJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgzWNFesa94WrH6D5nUebphrKd5lVfLQ',
    appId: '1:80375516886:android:6c8d88116775ce33158377',
    messagingSenderId: '80375516886',
    projectId: 'productivity-app-2bf41',
    storageBucket: 'productivity-app-2bf41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdoWi5rqSIqaj4BD8gIPmkyrXOnRk85WM',
    appId: '1:80375516886:ios:6e62492281b3ac0a158377',
    messagingSenderId: '80375516886',
    projectId: 'productivity-app-2bf41',
    storageBucket: 'productivity-app-2bf41.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdoWi5rqSIqaj4BD8gIPmkyrXOnRk85WM',
    appId: '1:80375516886:ios:6e62492281b3ac0a158377',
    messagingSenderId: '80375516886',
    projectId: 'productivity-app-2bf41',
    storageBucket: 'productivity-app-2bf41.firebasestorage.app',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZDJs-q9dUyLlZCM3IbyFbaw8TJezX0M',
    appId: '1:80375516886:web:eb66a6aad8eddb9d158377',
    messagingSenderId: '80375516886',
    projectId: 'productivity-app-2bf41',
    authDomain: 'productivity-app-2bf41.firebaseapp.com',
    storageBucket: 'productivity-app-2bf41.firebasestorage.app',
    measurementId: 'G-NGPJ3WR6GG',
  );
}
